FROM aruneko/texlive:latest

RUN tlmgr update --self --all

########### add user ###########
ARG USERNAME=user 
ARG GROUPNAME=user 
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} ${GROUPNAME} && \
    useradd -m -s /bin/bash -u ${UID} -g ${GID} ${USERNAME}
USER ${USERNAME}
################################

########### create workspace ###########
RUN mkdir /home/${USERNAME}/texsrc 
WORKDIR /home/${USERNAME}/texsrc
########################################

########### install packages via pip ###########
ADD ./.latexmkrc /home/${USERNAME} 
ADD . /home/${USERNAME}/texsrc/
################################################